-- CREATE TABLE [dbo].[mediaCategories] (
-- 	[categoryId] [tinyint] PRIMARY KEY,
-- 	[categoryNameAr] [nvarchar](100) NOT NULL,
--   [categoryNameEn] [nvarchar](100) NOT NULL,
--   [categoryType] [varchar](100) NOT NULL,
-- )
-- GO

-- insert into mediaCategories values (1, 'أخبار','News', 'articles')
-- insert into mediaCategories values (2, 'مقالات','Articles', 'articles')
-- insert into mediaCategories values (3, 'أنشطة','Activities', 'articles')
-- insert into mediaCategories values (4, 'برامج','Programs', 'articles')
-- insert into mediaCategories values (5, 'ألبوم','Albums', 'albums')
-- insert into mediaCategories values (6, 'الشرائح الرئيسية','Hero Slider', 'albums')
-- insert into mediaCategories values (7, 'روابط مواقع التواصل','Social Media Links', 'about')
-- insert into mediaCategories values (8, 'بيانات اساسية','Basic Info', 'about')
-- insert into mediaCategories values (9, 'بيانات الاتصال','Contact Info', 'about')
-- insert into mediaCategories values (10, 'روابط هامة','Useful Links', 'about')
-- insert into mediaCategories values (11, 'القبول والتسجيل','Admission', 'about')

-- CREATE TABLE [dbo].[abouts] (
-- 	[aboutId] [int] identity(1,1) PRIMARY KEY,
-- 	[aboutTitleAr] [nvarchar](100) NOT NULL,
-- [aboutTitleEn] [nvarchar](100) NOT NULL,
-- 	[aboutTextAr] [nvarchar](max) NOT NULL,
-- [aboutTextEn] [nvarchar](max) NOT NULL,
-- 	[aboutDate] [smalldatetime] NOT NULL,
-- 	[photoURL] [varchar](max) NULL,
--   [forCompany] [bit] NOT NULL,
--   [schoolId] [tinyint] NULL,
-- 	[stageId] [tinyint] NULL,
--   [empJobId] [int] NULL,
-- 	[categoryId] [tinyint] NULL,
-- )
-- GO

-- ALTER TABLE [dbo].[abouts] ALTER COLUMN [categoryId] [tinyint] NULL

-- sp_rename 'dbo.abouts.aboutTitle', 'aboutTitleAr', 'COLUMN'
-- sp_rename 'dbo.abouts.aboutText', 'aboutTextAr', 'COLUMN'
-- sp_rename 'dbo.abouts.isGlobal', 'forCompany', 'COLUMN'

-- ALTER TABLE [dbo].[abouts] ADD [aboutTitleEn] [nvarchar](100) NOT NULL
-- ALTER TABLE [dbo].[abouts] ADD [aboutTextEn] [nvarchar](max) NOT NULL
-- ALTER TABLE [dbo].[abouts] ALTER COLUMN [aboutTextAr] [nvarchar](max) NOT NULL
-- ALTER TABLE [dbo].[abouts] ADD [videoURL] [nvarchar](max) NULL

-- SELECT * FROM [dbo].[abouts]
-- GO

-- INSERT INTO [dbo].[abouts]
-- ( -- columns to insert data into
-- 	[aboutTitleAr],
--   [aboutTitleEn],
-- 	[aboutTextAr],
--   [aboutTextEn],
-- 	[aboutDate],
-- 	[photoURL],
--   [forCompany],
--   [schoolId],
-- 	[categoryId]
-- )
-- VALUES
-- ( -- first row: values for the columns in the list above
--   'مرحبا بكم',
--   'Welcome',
--   'منذ إنشائها عام 1434 هـ الموافق 2013 ميلاديا وتسهم مدارس الصدارة بدور ريادي في بناء أجيال جديدة قادرة على النهوض بالمملكة والمساهمة في تطور ونهضة الوطن.
-- وتعتبر مدارسنا من المدارس المميزة في شمال الرياض من حيث الجودة ومواكبة أحدث التقنيات في مجال التربية والتعليم واستخدام أفضل الأساليب التربوية والتدريسية من خلال طافم من المعلمين والمشرفين التربويين الذي يعملون بدأب ونشاط لتحقيق رؤية المدارس وإيصال رسالتها وتنفيذ أهدافها.‎',
--   'Since its establishment in 1434 AH corresponding to 2013 AD. The schools of the forerunner play a leading role in building new generations capable of advancing the Kingdom and contributing to the development and renaissance of the homeland.
-- Our schools are distinguished schools in the north of Riyadh in terms of quality and keep abreast of the latest technologies in the field of education and the use of the best educational and teaching methods through Tafm of teachers and educational supervisors who are working diligently to achieve the vision of schools and delivery of its mission and the implementation of its objectives.',
--   GETUTCDATE(),
--   'https://previews.dropbox.com/p/thumb/AAY8d1Wp3yFGvsljOWZTXoxG8G9tTGcqRVDTLhiOrIvgKabxhBBXqMbiPOmaRbifjIpqt8WzueGnThvJJSKSd6wS34wMn1hV6DLGX60MknIzuz-qyy9I9R9FEDZm3EVGHud85bEQdxaL-FIkUvO_kTmNCWrMVeRcrIbKC5fQM0EhdkouK-LkeFRY2QpYpeuuaZIYO3BG_nX3cPGRaQ20wYpnVBQpdf_b2MUoxC7fpCRgTHa6xXH4tq1iLN_VHMXXYMmTh5OAXiRUjj2-6uGuG6vBQurSFiZ5DeJhmYcFMwwGyaopFw6JtD5Bir8NNmXfOTJ7gdlg5W-52__dcft-tM11/p.jpeg',
--   0,
--   1,
--   8
-- ),
-- ( -- first row: values for the columns in the list above
--   'الرؤية',
--   'Vision',
--   'الريادة في تقديم تعليم عالي الجودة لإعداد جيلٍ واعٍ يرتقي إلى الصدارة على مستوى منطقة الرياض',
--   'To lead the way in providing high quality education to prepare a conscious generation to reach the forefront in the Riyadh region',
--   GETUTCDATE(),
--   'https://previews.dropbox.com/p/thumb/AAY8d1Wp3yFGvsljOWZTXoxG8G9tTGcqRVDTLhiOrIvgKabxhBBXqMbiPOmaRbifjIpqt8WzueGnThvJJSKSd6wS34wMn1hV6DLGX60MknIzuz-qyy9I9R9FEDZm3EVGHud85bEQdxaL-FIkUvO_kTmNCWrMVeRcrIbKC5fQM0EhdkouK-LkeFRY2QpYpeuuaZIYO3BG_nX3cPGRaQ20wYpnVBQpdf_b2MUoxC7fpCRgTHa6xXH4tq1iLN_VHMXXYMmTh5OAXiRUjj2-6uGuG6vBQurSFiZ5DeJhmYcFMwwGyaopFw6JtD5Bir8NNmXfOTJ7gdlg5W-52__dcft-tM11/p.jpeg',
--   0,
--   1,
--   8
-- ),
-- ( -- first row: values for the columns in the list above
--   'الرسالة',
--   'Mission',
--   'العمل على تسخير الإمكانيّات المادية والبشرية لرفع مستوى التحصيل العلمي والسلوكي للطلاب في سبيل الارتقاء للصدارة',
--   'Work on harnessing the material and human resources to raise the level of educational achievement and behavior of students in order to rise to the top',
--   GETUTCDATE(),
--   'https://previews.dropbox.com/p/thumb/AAY8d1Wp3yFGvsljOWZTXoxG8G9tTGcqRVDTLhiOrIvgKabxhBBXqMbiPOmaRbifjIpqt8WzueGnThvJJSKSd6wS34wMn1hV6DLGX60MknIzuz-qyy9I9R9FEDZm3EVGHud85bEQdxaL-FIkUvO_kTmNCWrMVeRcrIbKC5fQM0EhdkouK-LkeFRY2QpYpeuuaZIYO3BG_nX3cPGRaQ20wYpnVBQpdf_b2MUoxC7fpCRgTHa6xXH4tq1iLN_VHMXXYMmTh5OAXiRUjj2-6uGuG6vBQurSFiZ5DeJhmYcFMwwGyaopFw6JtD5Bir8NNmXfOTJ7gdlg5W-52__dcft-tM11/p.jpeg',
--   0,
--   1,
--   8
-- ),
-- ( -- first row: values for the columns in the list above
--   'الأهداف',
--   'Objectives',
--   'تقديم تعليم متميز و الرقي بسلوك الطلاب وفق قدراتهم واستعداداتهم للوصول إلى شخصية متوازنة متعلمة تحترم الرأي و الرأي الآخر و تتعايش في مجتمع آمن يتوفر فيه الإنصاف و العدالة و يسود فيه الحب و التعاون و يعمل على إلهام الطالب على الإبداع و التفكير الخلَّاق',
--   'To provide outstanding education and improve the behavior of students according to their abilities and readiness to reach a balanced balanced and educated person respect the opinion and the other opinion and coexist in a secure society in which there is equity and justice and prevail in love and cooperation and works to inspire students to creativity and creative thinking',
--   GETUTCDATE(),
--   'https://previews.dropbox.com/p/thumb/AAY8d1Wp3yFGvsljOWZTXoxG8G9tTGcqRVDTLhiOrIvgKabxhBBXqMbiPOmaRbifjIpqt8WzueGnThvJJSKSd6wS34wMn1hV6DLGX60MknIzuz-qyy9I9R9FEDZm3EVGHud85bEQdxaL-FIkUvO_kTmNCWrMVeRcrIbKC5fQM0EhdkouK-LkeFRY2QpYpeuuaZIYO3BG_nX3cPGRaQ20wYpnVBQpdf_b2MUoxC7fpCRgTHa6xXH4tq1iLN_VHMXXYMmTh5OAXiRUjj2-6uGuG6vBQurSFiZ5DeJhmYcFMwwGyaopFw6JtD5Bir8NNmXfOTJ7gdlg5W-52__dcft-tM11/p.jpeg',
--   0,
--   1,
--   8
-- ),
-- ( -- first row: values for the columns in the list above
--   'النشأة والتطور',
--   'Evolution and Development',
--   'تأسست المدرسة عام  2013م  الموافق للعام 1434هـ
-- ومن المعلوم أن النمو الذي تشهده المملكة العربية السعودية في المجالات كافة لابد أن يواكبه النمو الثقافي و المعرفي للأجيال فيها وعلى مختلف مستويات أعمارهم , و قد حملت مدارسنا (الصدارة ) على عاتقها أمانة الدور الريادي في وضع الخطط و البرامج التي تقوم بمسؤولية النهوض بأبنائنا إلى المستوى التربوي و التعليمي اللائقين و ليكون لها من اسمها نصيب فتتبوَّأ مركز الصدارة حاملة للتربية و التعليم كرسالة و مسؤولية و أمانة في مراحل التعليم كافة للبنين و البنات , و قد كان للقائمين على تأسيس المدارس و المشرفين عليها الرؤية العلمية و المعرفية المتناغمة مع الرؤية العصرية للمملكة (2030) بما يرِّسخ أسس الرقي بالمدارس و ينقلها من نجاح إلى نجاح أسمى في الميدانين السلوكي و المعرفي .
-- و قد تبنت المدارس بقسميها (البنين و البنات) أحدث الطرق للوصول إلى الأهداف المنشودة و المرسومة لها في بناء جيل إسلامي مثقف مدرك لأهمية مواكبة التقدم العصري المذهل .',
--   'The school was established in 2013 corresponding to 1434 AH
-- It is known that the growth witnessed by Saudi Arabia in all fields must be accompanied by the cultural and cognitive development of generations and at different levels of age. Our schools have assumed the responsibility of leading role in developing plans and programs that are responsible for raising our children to the level Education and education as a message, responsibility and trust in all stages of education for boys and girls. The founders of the schools and their supervisors have the scientific and cognitive vision consistent with the vision (2030) to establish the foundations of school development and move it from success to higher success in the behavioral and cognitive fields.
-- The schools have adopted the most modern ways to reach the desired goals in building an educated Islamic generation that is aware of the importance of keeping pace with modern progress.',
--   GETUTCDATE(),
--   'https://previews.dropbox.com/p/thumb/AAY8d1Wp3yFGvsljOWZTXoxG8G9tTGcqRVDTLhiOrIvgKabxhBBXqMbiPOmaRbifjIpqt8WzueGnThvJJSKSd6wS34wMn1hV6DLGX60MknIzuz-qyy9I9R9FEDZm3EVGHud85bEQdxaL-FIkUvO_kTmNCWrMVeRcrIbKC5fQM0EhdkouK-LkeFRY2QpYpeuuaZIYO3BG_nX3cPGRaQ20wYpnVBQpdf_b2MUoxC7fpCRgTHa6xXH4tq1iLN_VHMXXYMmTh5OAXiRUjj2-6uGuG6vBQurSFiZ5DeJhmYcFMwwGyaopFw6JtD5Bir8NNmXfOTJ7gdlg5W-52__dcft-tM11/p.jpeg',
--   0,
--   1,
--   8
-- ),
-- ( -- first row: values for the columns in the list above
--   'كلمة المشرف العام',
--   'Supervisor Message',
--   'استثمارنا في التعليم رغبة في التوصل إلى عقول قادرة على مواجهة آخر التحديثات والتحديات، نحن بحاجة لمواكبة مجتمعات أخرى حتى نساهم في تخريج جيل فريدٍ عقليًّا وعمليًّا، ونتبوأ مكاننا في صدارة مؤسسات التربية والتعليم',
--   'Our investment in education In order to reach minds capable of facing the latest updates and challenges, we need to keep pace with other communities so that we contribute to the generation of a unique generation mentally and practically, and we anticipate our place in the forefront of educational institutions',
--   GETUTCDATE(),
--   'https://previews.dropbox.com/p/thumb/AAY8d1Wp3yFGvsljOWZTXoxG8G9tTGcqRVDTLhiOrIvgKabxhBBXqMbiPOmaRbifjIpqt8WzueGnThvJJSKSd6wS34wMn1hV6DLGX60MknIzuz-qyy9I9R9FEDZm3EVGHud85bEQdxaL-FIkUvO_kTmNCWrMVeRcrIbKC5fQM0EhdkouK-LkeFRY2QpYpeuuaZIYO3BG_nX3cPGRaQ20wYpnVBQpdf_b2MUoxC7fpCRgTHa6xXH4tq1iLN_VHMXXYMmTh5OAXiRUjj2-6uGuG6vBQurSFiZ5DeJhmYcFMwwGyaopFw6JtD5Bir8NNmXfOTJ7gdlg5W-52__dcft-tM11/p.jpeg',
--   0,
--   1,
--   8
-- )

-- insert OrganizatioalChart
-- INSERT INTO [dbo].[abouts]
-- ( -- columns to insert data into
-- 	[aboutTitleAr],
--   [aboutTitleEn],
-- 	[aboutTextAr],
--   [aboutTextEn],
-- 	[aboutDate],
--   [forCompany],
--   [schoolId],
-- 	[categoryId]
-- )
-- VALUES (
--   'الهيكل التنظيمي للمدارس',
--   'Schools Organizatioal Chart',
--   'https://i.ibb.co/YBSBR2d/Organizatioal-Chart.png',
--   'https://i.ibb.co/YBSBR2d/Organizatioal-Chart.png',
--   GETUTCDATE(),
--   0,
--   1,
--   8
-- )
-- GO

-- INSERT INTO [dbo].[abouts]
-- ( -- columns to insert data into
-- 	[aboutTitleAr],
--   [aboutTitleEn],
-- 	[aboutTextAr],
--   [aboutTextEn],
-- 	[aboutDate],
--   [forCompany],
--   [schoolId],
-- 	[categoryId]
-- )
-- VALUES
-- (
--   'العنوان',
--   'Address',
--   '107 حي النرجس - الرياض - المملكة العربية السعودية ‎',
--   '107، An Narjis, Riyadh 13323, Saudi Arabia',
--   GETUTCDATE(),
--   0,
--   1,
--   9
-- ),
-- (
--   'التلفون',
--   'Phone',
--   '+966538450055‎',
--   '+966538450055',
--   GETUTCDATE(),
--   0,
--   1,
--   9
-- ),
-- (
--   'الإيميل',
--   'Email',
--   '‎assadaraSchools@gmail.com',
--   'assadaraSchools@gmail.com',
--   GETUTCDATE(),
--   0,
--   1,
--   9
-- ),
-- (
--   'الفاكس',
--   'Fax',
--   '‎+966538450055',
--   '+966538450055',
--   GETUTCDATE(),
--   0,
--   1,
--   9
-- ),
-- (
--   'الرمز البريدي',
--   'Postal Code',
--   '‎1234566',
--   '1234566',
--   GETUTCDATE(),
--   0,
--   1,
--   9
-- ),
-- (
--   'مواعيد العمل',
--   'Working Hours',
--   'الأحد - الخميس 06:30 ص - 02:00 م‎',
--   'Sunday-Thursday 06:30 AM - 02:00 PM',
--   GETUTCDATE(),
--   0,
--   1,
--   9
-- )

-- INSERT INTO [dbo].[abouts]
-- ( -- columns to insert data into
-- 	[aboutTitleAr],
--   [aboutTitleEn],
-- 	[aboutTextAr],
--   [aboutTextEn],
-- 	[aboutDate],
--   [forCompany],
--   [schoolId],
-- 	[categoryId]
-- )
-- VALUES
-- (
--   'تويتر',
--   'Twitter',
--   'https://twitter.com/Assadarah',
--   'https://twitter.com/Assadarah',
--   GETUTCDATE(),
--   0,
--   1,
--   7
-- ),
-- (
--   'يوتيوب',
--   'Youtube',
--   'https://www.youtube.com/user/assadarah',
--   'https://www.youtube.com/user/assadarah',
--   GETUTCDATE(),
--   0,
--   1,
--   7
-- ),
-- (
--   'فايسبوك',
--   'Facebook',
--   'https://www.facebook.com/mohammad.wahba.58',
--   'https://www.facebook.com/mohammad.wahba.58',
--   GETUTCDATE(),
--   0,
--   1,
--   7
-- ),
-- (
--   'انستجرام',
--   'Instagram',
--   'https://www.instagram.com/explore/locations/148878629/',
--   'https://www.instagram.com/explore/locations/148878629/',
--   GETUTCDATE(),
--   0,
--   1,
--   7
-- ),
-- (
--   'سناب شات',
--   'Snapchat',
--   'https://www.snapchat.com/',
--   'https://www.snapchat.com/',
--   GETUTCDATE(),
--   0,
--   1,
--   7
-- )

-- INSERT INTO [dbo].[abouts]
-- ( -- columns to insert data into
-- 	[aboutTitleAr],
--   [aboutTitleEn],
-- 	[aboutTextAr],
--   [aboutTextEn],
-- 	[aboutDate],
--   [forCompany],
--   [schoolId],
-- 	[categoryId]
-- )
-- VALUES
-- (
--   'وزارة التعليم',
--   'Ministry Of Education',
--   'https://www.moe.gov.sa',
--   'https://www.moe.gov.sa',
--   GETUTCDATE(),
--   0,
--   1,
--   10
-- ),
-- (
--   'بوابة نور',
--   'Noor Portal',
--   'https://noor.moe.gov.sa/noor/login.aspx',
--   'https://noor.moe.gov.sa/noor/login.aspx',
--   GETUTCDATE(),
--   0,
--   1,
--   10
-- ),
-- (
--   'موقع المدارس الإداري',
--   'School Admin Site',
--   'http://www.Assadarah1.com',
--   'http://www.Assadarah1.com',
--   GETUTCDATE(),
--   0,
--   1,
--   10
-- ),
-- (
--   'المناهج الدراسية',
--   'School Books',
--   'http://ebook.sa/default.aspx',
--   'http://ebook.sa/default.aspx',
--   GETUTCDATE(),
--   0,
--   1,
--   10
-- )

-- INSERT INTO [dbo].[abouts]
-- ( -- columns to insert data into
-- 	[aboutTitleAr],
--   [aboutTitleEn],
-- 	[aboutTextAr],
--   [aboutTextEn],
-- 	[aboutDate],
--   [forCompany],
--   [schoolId],
-- 	[categoryId]
-- )
-- VALUES
-- (
--   'سياسة القبول',
--   'Admission Policy',
--   '<h3>سياسة التسجيل</h3>
-- <p>
--   الرسوم لا تشمل الضريبة المضافة.
--   الخصم النقدي 1000 ريال لكل طالب عند السداد الكامل للعام الدراسي  وينتهي الخصم النقدي للسداد بعد أسبوعين من بداية الدراسة.
--   دفعة التسجيل 2000 ريال تحسم من الرسوم تدفع مرة واحدة عند التسجيل ولا ترد.
--   يسدد ولي الأمر كامل رسوم  الفصل الأول قبل انتهاء الربع الأول  ورسوم الفصل الثاني قبل انتهاء الربع الثالث وذلك عند اختيار طريقة السداد على قسطين.
--   لن يتم استلام الكتب أو الزي حتي سداد رسومهما.
-- </p>
-- <h3>نظام الانسحاب</h3>
-- <ul>
--   <li>يعد تاريخ استلام المدارس لخطاب الانسحاب هو التاريخ المعتبر وليس تاريخ الخطاب</li>
--   <li>عند إبلاغ المدارس بانسحاب الطالب قبل بداية الفصل الدراسي فإنه يحق للطالب استرجاع كامل الرسوم الدراسيةبعد خصم رسوم الكتب والزي كاملا اذا استخدم الزي والكتب.</li>
--   <li>يحسم 25% من رسوم الفصل الدراسي  عند انسحاب الطالب خلال الأسبوع الثاني من الفصل الدراسي.</li>
--   <li>يحسم 50% من رسوم الفصل الدراسي  عند انسحاب الطالب خلال الأسبوع الثالث من الفصل الدراسي.</li>
--   <li>يحسم 100% من رسوم الفصل الدراسي  عند انسحاب الطالب خلال الأسبوع الرابع من الفصل الدراسي.</li>
--   <li>عند الانسحاب خلال العام الدراسي يدفع الطالب المتبقي من القيمة الكتب الفعلية للكتب  500 ريال للروضة، و1500 ريال للابتدائي و2000ريال للمتوسط والثانوي</li>
--   <li>عند الانسحاب تخصم قيمة الخصم الذي تم عند التسجيل.</li>
-- </ul>',
--   '<h3>Registration Policy</h3>
-- <p>
--   If full fee is paid, the contract will be for whole Academic Year.
--     Cash discount SR 1000 per Learner upon payment at the beginning of the academic year for full year. The cash payment discount expires two weeks after the beginning of the academic year.
--     A registration non-refundable down payment of SR. 2000 has to be paid and will automatically bededucted from the fees (upon first registration only).
--     Transportation Fees is 5000 Two ways, and 3000 One way for one Academic Year.
--     The entire first semester fees are to be paid by the parent / guardian before the end of the first quarter and for the second semester the fees have to be paid before the end of the third quarter if the option of two-installment is chosen.
--     Books and uniforms will not be received until their cost is paid.
-- </p>
-- <h3>Withdrawal Policy</h3>
-- <ul>
--   <li>The date of receiving the withdrawal letter is the official date not the date typed on the withdrawal letter.</li>
--   <li>In case of withdrawal before the academic year starts, all school fees are completely refundable except books and uniform fees if uniform or books are used.</li>
--   <li>25% of the semester fees will be deducted in case of withdrawal during the second week of the semester.</li>
--   <li>50% of the semester fees will be deducted in case of withdrawal during the third week of the semester.</li>
--   <li>100% of the semester fees will be deducted in case of withdrawal during the fourth week of the semester.</li>
--   <li>Upon withdrawal during school year, the complete fee of books is deductible as follows: SR. 500 for Kindergarten, SR. 1500 for Primary School and SR. 2,000 for Middle & High Schools.</li>
--   <li>Discounted price is deductible as well.</li>
-- </ul>',
--   GETUTCDATE(),
--   0,
--   1,
--   11
-- ),
-- (
--   'إجراءات التسجيل',
--   'Registration Procedures',
--   '<h3>تعليمات التسجيل</h3>
-- <ul>
--   <li>أدخل جميع التفاصيل بشكل كامل وصحيح.</li>
--   <li>يجب أن يكون الاسم و تاريخ الميلاد وفقًا لجواز السفر.</li>
--   <li>يجب توفير رقمي جوال على الأقل.</li>
--   <li>يجب أن يوافق ولي الأمر على الشروط.</li>
-- </ul>
-- <h3>المستندات المطلوبة</h3>
-- <ul>
--   <li>نسخة جواز سفر المتعلمين</li>
--   <li>نسخة من بطاقة الهوية الوطنية / بطاقة تصريح الإقامة للمتعلمين</li>
--   <li>نسخة من شهادة ميلاد المتعلمين</li>
--   <li>نسخة من جواز ولي الأمر</li>
--   <li>نسخة من بطاقة الهوية الوطنية / وصي الإقامة لشخصين</li>
--   <li>شهادة التخليص المالي / رسالة من المدرسة السابقة</li>
--   <li>شهادة التخرج من المدرسة / قبول سحب المتعلمين من المدرسة السابقة</li>
--   <li>مستند نقل الطلب على نظام نور(في حالة النقل).</li>
--   <li>اكتمال سلسلة بطاقات النتائج من KG إلى الصف الأخير</li>
--   <li>شهادة التطعيم</li>
--   <li>شهادة طبية</li>
-- </ul>
-- <h3>ملاحظات عامة</h3>
-- <p>
--   سيخضع كل متعلم عند التسجيل لاختبار القبول أو امتحان التقييم أو التقييم العام وفقًا لمتطلبات المجلس الأكاديمي. يمكن إلغاء هذا الأمر في بعض الحالات بناءً على تقدير المدير الأكاديمي أو أحد أعضاء المجلس الأكاديمي.
--     سيخضع كل متعلم عند التسجيل وأولياء أموره لمقابلة أكاديمية وإدارية وطبية ونفسية وفقًا لسياسة المدرسة. يمكن إلغاء هذه المقابلة وفقًا لتقدير المجالس الأكاديمية في أي وقت قبل وضع اللمسات الأخيرة على عملية القبول ويمكن أن تعقد في مرحلة لاحقة. يمكن تفويض المقابلة لأي من أعضاء المجلس الأكاديمي أو أي من أعضاء الفريق الأكاديمي من المستشارين الأكاديميين للمعلمين.
--     في بعض الحالات ، الأكاديمية أو الطبية أو أي شيء آخر ، قد تقرر المدرسة وضع شروط قبل الموافقة على قبول المسجل في المدارس.
-- </p>
-- <p>
--     للمتعلمين القادمين من الخارج سيتعين على جميع المتعلمين الحصول على بطاقة معادلة ممتلئة من الأسد والحصول على موافقة من مكتب القبول والامتحانات في الرياض الذي يعمل تحت إدارة وزارة التربية والتعليم بالمملكة العربية السعودية.
--     بناءً على القبول ، يمكن إصدار خطاب بناءً على طلب ولي الأمر للقبول بالقبول في الأسد.
-- </p>
-- <p>
--     وفقًا لسياسة القبول التي تم تحديثها في الأول من مايو 2019 ، سيتعين إكمال أي عمليات قبول من خلال رسم حجز المقاعد بحد أدنى SAR. من 2000 حتى 31 يوليو 2019. جميع موافقات القبول من 1 أغسطس 2019 ستطبق على الدفع بالكامل من أجل إكمال القبول في Asadarah.
--     بعد دفع الرسوم كاملة ، سوف يتلقى المتعلم Uniform & Books. حاشية يجب استلام كتب الهوية العربية والإسلامية والاجتماعية العربية / الوطنية من المدرسة السابقة من المسجلين الجدد وفقًا لتوجيهات وزارة التربية والتعليم وهي مسؤولية الأوصياء على استلامها.
--     سيؤدي الانتهاء من قبول المسجل إلى إرسال رسالة نصية قصيرة إلى رقم الجوال Guardians المحفوظة في النظام باستخدام بيانات اعتماد تسجيل الدخول إلى حساب الصدارة (الباحث العلمي)
-- </p>',
--   '<h3>Registration Rules</h3>
-- <ul>
--   <li>Enter all details fully and correctly.</li>
--   <li>Name and DoB must be according to the passport.</li>
--   <li>At least two mobile numbers must be provided.</li>
--   <li>The conditions will have to be agreed by the Guardian before acceptance.</li>
-- </ul>
-- <h3>Required Documents</h3>
-- <ul>
--   <li>Learners’ Passport Copy</li>
--   <li>Learners’ National Identity Card / Residence Permit Card Copy</li>
--   <li>Learners’ Birth Certificate Copy</li>
--   <li>Two Guardians’ Passport Copy</li>
--   <li>Two Guardians’ National Identity Card / Residence Permit Card Copy</li>
--   <li>Financial Clearance Certificate / Letter from previous school</li>
--   <li>School Leaving Certificate / Acceptance of the Learners’ Withdrawal from previous school</li>
--   <li>Transfer request document on Noor system (In case of Transfer).</li>
--   <li>Series of Result Cards from KG to last grade completed</li>
--   <li>Vaccination Certification</li>
--   <li>Medical Certificate</li>
-- </ul>
-- <h3>Notes</h3>
-- <p>
--     Every learner upon registration will be subject to an Admission Test, Assessment Exam or General Assessment as per Academic Board’s requirements. This can be annulled in certain cases upon discretion of the Academic Director or any one of the Academic Board members.
--     Every learner upon registration & their parents will be subject to an Academic, Administrative, Medical as well as Psychological interview as per School’s Policy. This interview can be as annulled subject to Academic Boards’ discretion at any time prior to finalization of admission process and is subject to be convened at a later stage. The interview can be delegated to any one of the Academic Board’s members or any of the Academic Team members from Academic Advisors to Educators.
--     In certain cases, Academic, Medical or any other whatsoever, the School might decide to set conditions prior to approving the admission of a registrant to schools.
-- </p>
-- <p>
--     For learners coming from overseas; all learners will have to get filled equivalency card from Assadarah and get approved from Admissions & Examinations Office in Riyadh that works under the directorate of Ministry of Education, Kingdom of Saudi Arabia.
--     Upon acceptance, a letter upon request of the Guardian can be issued for acceptance of Admission to Assadarah.
-- </p>
-- <p>
--     As per Admissions Policy updated on 1st of May, 2019, any acceptances will have to be completed by a seat reservation fee of minimum SAR. 2,000 till the 31st of July, 2019. All admission acceptances from 1st of August, 2019 will be applicable to pay in full in order to complete the admission at Assadarah.
--     After payment of full fee, the learner will receive Uniform & Books. N.B. Arabic, Islamic & Social Arabic / National Identity books have to be received from previous school from new registrants as per MoE directives and is guardians’ responsibility to receive.
--     Finalization of acceptance of registrant will lead to an SMS sent to Guardians’ Mobile Number saved in system with Login Credentials to (Scholar) account.
-- </p>',
--   GETUTCDATE(),
--   0,
--   1,
--   11
-- ),
-- (
--   'الرسوم',
--   'Fees',
--   '<h3>رسوم الدراسة</h3>
-- <ul>
--   <li>رياض الأطفال 12000 ريال </li>
--   <li>الابتدائي والمتوسط 18000</li>
--   <li>الثانوي 24000 ريال </li>
-- </ul>
-- <h3>رسوم النقل</h3>
-- <ul>
--   <li>ذهاب وإياب: 5000</li>
--   <li>ذهاب فقط: 3000</li>
--   <li>إياب فقط: 3000</li>
-- </ul>',
--   '<h3>Study Fees</h3>
-- <ul>
--   <li>KG 12000 SR</li>
--   <li>Primary and Intermediate Stages : 18000 SR </li>
--   <li>Secondary Stage : 24000 SR</li>
-- </ul>
-- <h3>Transportation Fees</h3>
-- <ul>
--   <li>go and return: 5000 </li>
--   <li>go only: 3000</li>
--   <li>return only: 3000</li>
-- </ul>',
--   GETUTCDATE(),
--   0,
--   1,
--   11
-- )

-- SELECT * FROM [dbo].[abouts]
-- GO

-- Update rows in table '[dbo].[abouts]'
-- UPDATE [dbo].[abouts]
-- SET
--   [aboutTitleAr] = 'تاريخ المدارس',
--   [aboutTitleEn] = 'Schools History'
-- WHERE [aboutId] = 5
-- GO

-- add 4 relations [employeesJobs - departments - schools - mediaCategories]
---------------------------------------------------------------------------

-- ALTER TABLE [dbo].[abouts] DROP CONSTRAINT [FK_employeesJobs_about]
-- ALTER TABLE [dbo].[abouts]
-- ADD CONSTRAINT [FK_employeesJobs_abouts] FOREIGN KEY([empJobId])
-- REFERENCES [dbo].[employeesJobs] ([empJobId])
-- ON UPDATE CASCADE
-- ON DELETE SET NULL
-- GO

-- ALTER TABLE [dbo].[abouts] DROP CONSTRAINT [FK_departments_about]
-- ALTER TABLE [dbo].[abouts]
-- ADD CONSTRAINT [FK_departments_abouts] FOREIGN KEY([stageId])
-- REFERENCES [dbo].[departments] ([departmentId])
-- ON UPDATE CASCADE
-- ON DELETE SET NULL
-- GO

-- ALTER TABLE [dbo].[abouts] DROP CONSTRAINT [FK_schools_about]
-- ALTER TABLE [dbo].[abouts]
-- ADD CONSTRAINT [FK_schools_abouts] FOREIGN KEY([schoolId])
-- REFERENCES [dbo].[schools] ([schoolId])
-- ON UPDATE CASCADE
-- ON DELETE SET NULL
-- GO

-- ALTER TABLE [dbo].[abouts] DROP CONSTRAINT [FK_mediaCategories_about]
-- ALTER TABLE [dbo].[abouts]
-- ADD CONSTRAINT [FK_mediaCategories_abouts] FOREIGN KEY([categoryId])
-- REFERENCES [dbo].[mediaCategories] ([categoryId])
-- ON UPDATE CASCADE
-- ON DELETE SET NULL
-- GO

-----------------------------------------------------------------
-- ALTER TABLE [dbo].[articles] ADD [isImportant] [bit] NOT NULL
-- ALTER TABLE [dbo].[albums] ADD [isImportant] [bit] NOT NULL
-- ALTER TABLE [dbo].[articles] DROP COLUMN [isImportant]
-- ALTER TABLE [dbo].[albums] DROP COLUMN [isImportant]
-- ALTER TABLE [dbo].[articles] ADD [displayAlsoAt] [varchar](10) NOT NULL DEFAULT('none')
-- ALTER TABLE [dbo].[albums] ADD [displayAlsoAt] [varchar](10) NOT NULL DEFAULT('none')
-- sp_rename 'dbo.articles.isGlobal', 'forCompany', 'COLUMN'
-- GO
-- sp_rename 'dbo.albums.isGlobal', 'forCompany', 'COLUMN'
-- GO
-- sp_rename 'dbo.about', 'abouts'
-- GO
-----------------------------------------------------------------
-- -- displayAlsoAt: [company - school - both - none]
-- -- to specify which [article and/or album] should be displayed at a higher rank [global - school]
----------------------------------------------------------------------------------------------------
-- CREATE TABLE [dbo].[articles] (
-- 	[articleId] [int] identity(1,1) PRIMARY KEY,
-- 	[articleTitleAr] [nvarchar](100) NOT NULL,
-- 	[articleTitleEn] [nvarchar](100) NOT NULL,
-- 	[articleTextAr] [nvarchar](max) NOT NULL,
-- 	[articleTextEn] [nvarchar](max) NOT NULL,
--  [authorNameAr] [nvarchar](100) NULL,
--  [authorNameEn] [nvarchar](100) NULL,
-- 	[articleDate] [smalldatetime] NOT NULL,
-- 	[mainPhotoURL] [varchar](max) NULL,
-- 	[photosURLs] [varchar](max) NULL,
-- 	[videosURLs] [varchar](max) NULL,
--  [displayAlsoAt] [varchar](10) NOT NULL,
--  [forCompany] [bit] NOT NULL,
--  [schoolId] [tinyint] NULL,
-- 	[stageId] [tinyint] NULL,
--  [empJobId] [int] NULL,
-- 	[categoryIds] [varchar](max) NULL,
--  [approved] [bit] NOT NULL,
--  [enabled] [bit] NOT NULL,
--  [keywords] [nvarchar](max) NULL,
-- )
-- GO

-- Insert rows into table '[dbo].[articles]'
-- INSERT INTO [dbo].[articles]
-- ( -- columns to insert data into
--   [articleTitleAr],
--   [articleTitleEn],
--   [articleTextAr],
--   [articleTextEn],
--   [authorNameAr],
--   [authorNameEn],
--   [mainPhotoURL],
--   [articleDate],
--   [displayAlsoAt],
--   [forCompany],
--   [schoolId],
--   [stageId],
--   [categoryIds],
--   [approved],
--   [enabled],
--   [keywords]
-- )
-- VALUES
-- ( -- first row: values for the columns in the list above
--   'حفل تخرج طلاب مدارس الصدارة الأهليه',
--   'Graduation Ceremony for students of Assadara schools',
--   'حفل تخرج وتكريم طلاب الصف الثالث الثانوي بمدارس الصدارة الأهليه وكان حفل مميز بحضور مالك المدارس الأستاذ/خالد الرسيني وقائدها /الإستاذ مساعد الفهد وجميع منسوبيها واولياء الامور وجميع الخريجين الف مبروك للجميع.
-- تضمن الحفل العديد من الفقرات التي شارك بها الطلاب الخريجين بالإضافة إلى كلمة قائد المدرسة والتي رحب فيها بالسادة الضيوف وأولياء أمور الطلاب كما قام بتكريم الطلاب وتوزيع الجوائز والدروع عليهم. تضمن الحفل فقرات باللغتين العربية والإنجليزية بالإضافة إلى مسيرة الطلاب الخريجين ثم انتهى بالعشاء الذي شارك فيها طلاب المدارس وأولياء الأمور ومنسوبي المدارس.
-- ',
--   'A ceremony was held in the presence of the owner of the schools, Mr. Khalid Al-Risini, and its leader / Mr. Al-Fahad, all its employees, parents and all graduates. Congratulations to all.The ceremony included several sections in which the graduate students participated in addition to the speech of the school leader, in which he welcomed the guests and parents of the students. He also honored the students and distributed prizes and shields to them. The ceremony included sections in Arabic and English in addition to the march of graduate students and ended with a dinner attended by school students, parents and school staff.',
--   'أحمد وهبة',
--   'Ahmed Wahba',
--   'https://previews.dropbox.com/p/thumb/AAY8d1Wp3yFGvsljOWZTXoxG8G9tTGcqRVDTLhiOrIvgKabxhBBXqMbiPOmaRbifjIpqt8WzueGnThvJJSKSd6wS34wMn1hV6DLGX60MknIzuz-qyy9I9R9FEDZm3EVGHud85bEQdxaL-FIkUvO_kTmNCWrMVeRcrIbKC5fQM0EhdkouK-LkeFRY2QpYpeuuaZIYO3BG_nX3cPGRaQ20wYpnVBQpdf_b2MUoxC7fpCRgTHa6xXH4tq1iLN_VHMXXYMmTh5OAXiRUjj2-6uGuG6vBQurSFiZ5DeJhmYcFMwwGyaopFw6JtD5Bir8NNmXfOTJ7gdlg5W-52__dcft-tM11/p.jpeg',
--   GETUTCDATE(),
--   'both',
--   0,
--   1,
--   1,
--   '1',
--   1,
--   1,
--   'assadara schools graduation'
-- )
-- INSERT INTO [dbo].[articles]
-- ( -- columns to insert data into
--   [articleTitleAr],
--   [articleTitleEn],
--   [articleTextAr],
--   [articleTextEn],
--   [authorNameAr],
--   [authorNameEn],
--   [mainPhotoURL],
--   [articleDate],
--   [displayAlsoAt],
--   [forCompany],
--   [schoolId],
--   [stageId],
--   [categoryIds],
--   [approved],
--   [enabled],
--   [keywords]
-- )
-- VALUES
-- ( -- first row: values for the columns in the list above
--   'تمثيل مدارس الصدارة الاهليه في مسابقة فيرست ليقو لي',
--   'Representing the premier private schools in the First Lego Le Competition',
--   'شارك طلاب مدارس الصدارة الاهليه في مسابقة (Fll) فرست ليقو لي وحصلوا على المركز الثالث في التقييم على مستوى مدارس الرياض ولله الحمد. كانت المسابقه جميله حصد فيها طلابنا العلم والمعرفه وكأس المركز الثالث والعديد من الميداليات.
-- أشرف على تدريب وإعداد الطلاب للمسابقة معلموا الحاسب الآلي والروبوت حيث كان الطلاب يشاركون في ورشة عمل لمدة شهر تدربوا فيه على تنفيذ العديد من العمليات المتقدمة في التعامع مع الروبوت. ',
--   'The students of the private schools participated in the Fll competition, and they won the third place in the assessment at the level of the schools of Riyadh and all praise. It was a beautiful race where our students won the science and knowledge, the third place trophy and many medals.
-- The training and preparation of students for the competition was supervised by computer and robot teachers where students participated in a one-month workshop where they practiced many advanced robotics operations.',
--   'أحمد وهبة',
--   'Ahmed Wahba',
--   'https://previews.dropbox.com/p/thumb/AAY8d1Wp3yFGvsljOWZTXoxG8G9tTGcqRVDTLhiOrIvgKabxhBBXqMbiPOmaRbifjIpqt8WzueGnThvJJSKSd6wS34wMn1hV6DLGX60MknIzuz-qyy9I9R9FEDZm3EVGHud85bEQdxaL-FIkUvO_kTmNCWrMVeRcrIbKC5fQM0EhdkouK-LkeFRY2QpYpeuuaZIYO3BG_nX3cPGRaQ20wYpnVBQpdf_b2MUoxC7fpCRgTHa6xXH4tq1iLN_VHMXXYMmTh5OAXiRUjj2-6uGuG6vBQurSFiZ5DeJhmYcFMwwGyaopFw6JtD5Bir8NNmXfOTJ7gdlg5W-52__dcft-tM11/p.jpeg',
--   GETUTCDATE(),
--   'none',
--   0,
--   1,
--   2,
--   '1',
--   1,
--   1,
--   'assadara schools graduation'
-- ),
-- ( -- first row: values for the columns in the list above
--   'احتفال اليوم الوطني',
--   'National Day Celebration',
--   'احتفلت مدارس الصدارة الأهلية باليوم الوطني الـ88 للملكة العربية السعودية بحضور قادة الأقسام والمعلمين والإداريين وذلك يوم الثلاثاء الموافق : 1440/1/8 هـ حيث تزنينت المدرسة بالأعلام الخضراء والشعارات والكلمات الوطنية بمشاركة الطلاب والمعلمين
-- وتنوعت احتفالات المدرسة بالفقرات الوطنية والبرامج المتنوعة ، التى من شأنها أن تساهم في تعزيز الوطنية لدى طلاب المدارس وتعريفهم بقيمة الولاء للوطن وبأهمية التعليم ودوره الكبير في نهضة الوطن وتقدمه',
--   'Al-Sidra National Schools celebrated the 88th National Day of the Kingdom of Saudi Arabia in the presence of the heads of departments, teachers and administrators on Tuesday 1440/1/8 H. The school was decorated with green flags, slogans and national words with the participation of students and teachers.
-- The school celebrations varied with national chapters and various programs, which would contribute to enhancing patriotism among school students and introducing them to the value of loyalty to the nation and the importance of education and its great role in the renaissance and progress of the country.',
--   'أحمد وهبة',
--   'Ahmed Wahba',
--   'https://previews.dropbox.com/p/thumb/AAY8d1Wp3yFGvsljOWZTXoxG8G9tTGcqRVDTLhiOrIvgKabxhBBXqMbiPOmaRbifjIpqt8WzueGnThvJJSKSd6wS34wMn1hV6DLGX60MknIzuz-qyy9I9R9FEDZm3EVGHud85bEQdxaL-FIkUvO_kTmNCWrMVeRcrIbKC5fQM0EhdkouK-LkeFRY2QpYpeuuaZIYO3BG_nX3cPGRaQ20wYpnVBQpdf_b2MUoxC7fpCRgTHa6xXH4tq1iLN_VHMXXYMmTh5OAXiRUjj2-6uGuG6vBQurSFiZ5DeJhmYcFMwwGyaopFw6JtD5Bir8NNmXfOTJ7gdlg5W-52__dcft-tM11/p.jpeg',
--   GETUTCDATE(),
--   'both',
--   1,
--   null,
--   null,
--   '1',
--   1,
--   1,
--   'assadara schools graduation'
-- ),
-- ( -- first row: values for the columns in the list above
--   'نادي الروبوت',
--   'The Robot Club',
--   'تأسس نادي الروبوت التابع لمدارس الصدارة في الفصل الأول من العام 1434/ 1435 هـ وقد شارك النادي في بطولات الروبوت على مستوى الرياض وعلى مستوى المملكة وحقق بفضل الله العديد من الإنجازات منها :
-- - الحصول على المركز الأول في مسابقة Robocop على مستوى الرياض 1436/ 1437 هـ
-- - الحصول على المركز الثاني في مسابقة VEXعلى مستوى الرياض 2014م وتأهله للتصفيات النهائية على مستوى المملكة وحصوله على المركز الثالث .
-- - الجدير بالذكر أن المدارس تقدم حصة إثرائية أسبوعية في الروبوت لطلاب المرحلة الابتدائية والمتوسطة يتعلم من خلالها الطالب أساسيات',
--   'The robot club of the top schools was founded in the first quarter of the year 1434/1435 H. The club has participated in the robotics championships in Riyadh and Kingdom level.
-- - Obtained the first place in the competition Robocop at the level of Riyadh 1436/1437 e
-- - Get the second place in the competition VEX at the level of Riyadh 2014 and qualify for the finalists in the Kingdom and get the third place.
-- - It is worth noting that the schools offer a weekly enrichment lesson in robot for primary and middle school students through which the student learns the basics',
--   'أحمد وهبة',
--   'Ahmed Wahba',
--   'https://previews.dropbox.com/p/thumb/AAY8d1Wp3yFGvsljOWZTXoxG8G9tTGcqRVDTLhiOrIvgKabxhBBXqMbiPOmaRbifjIpqt8WzueGnThvJJSKSd6wS34wMn1hV6DLGX60MknIzuz-qyy9I9R9FEDZm3EVGHud85bEQdxaL-FIkUvO_kTmNCWrMVeRcrIbKC5fQM0EhdkouK-LkeFRY2QpYpeuuaZIYO3BG_nX3cPGRaQ20wYpnVBQpdf_b2MUoxC7fpCRgTHa6xXH4tq1iLN_VHMXXYMmTh5OAXiRUjj2-6uGuG6vBQurSFiZ5DeJhmYcFMwwGyaopFw6JtD5Bir8NNmXfOTJ7gdlg5W-52__dcft-tM11/p.jpeg',
--   GETUTCDATE(),
--   'both',
--   0,
--   1,
--   3,
--   '1',
--   1,
--   1,
--   'assadara schools graduation'
-- ),
-- ( -- first row: values for the columns in the list above
--   'مدارس الصدارة و الـآيلتس العالمي لتعليم اللغة الإنجليزية و اختباراتها',
--   'IELTS International Language Schools and their tests',
--   'نظام تقييم اللغة الإنجليزية الدولي الـ "IELTS" هو امتحان اللغة الإنجليزية الأكثر شهرة على مستوى العالم، حيث يقدم أكثر من مليوني شخص حول العالم الامتحان كل عام.

-- الأنشطة :
-- تدريب الطلاب على المحادثة بأعلى مستوى مع الناطقين بها
-- تهيئة الطالب وتدريبه لاجتياز الاختبار العالمي الـ "IELTS .
-- إعداد الطالب لمتطلبات سوق العمل مستقبلا .
-- إعداد الطالب دراسيا لاجتياز اختباراته بسهولة
-- مناهج إضافية عن الاختبارات الدولية الـ "IELTS

-- المميزات
-- قاعات تدريب بأعلى المستويات العالمية في التعليم
-- محاضرون متخصصون في تعليم اللغة الإنجليزية بمعايير عالمية
-- إقامة ورش عمل وزيارات خارجية للمتميزين داخل وخارج المملكة
--  برمجة الروبوت بالاستعانة بمجموعة من الروبوتات التعليمية التي توفرها المدارس لطلبة النادي',
--   'IELTS is the world most widely recognized English exam, with more than 2 million people taking the exam each year.

-- Activities:
-- Train students to converse at the highest level with their native speakers
-- Train and train the student to pass the IELTS Global Test.
-- Preparing the student for the requirements of the labor market in the future.
-- Prepare the student to pass the tests easily
-- Additional approaches to IELTS international tests

-- Advantages
-- World-class training halls in education
-- Specialists in teaching English language with international standards
-- Organizing workshops and external visits for distinguished individuals inside and outside the Kingdom
--  Programming robots using a set of educational robots provided by schools to club students',
--   'أحمد وهبة',
--   'Ahmed Wahba',
--   'https://previews.dropbox.com/p/thumb/AAY8d1Wp3yFGvsljOWZTXoxG8G9tTGcqRVDTLhiOrIvgKabxhBBXqMbiPOmaRbifjIpqt8WzueGnThvJJSKSd6wS34wMn1hV6DLGX60MknIzuz-qyy9I9R9FEDZm3EVGHud85bEQdxaL-FIkUvO_kTmNCWrMVeRcrIbKC5fQM0EhdkouK-LkeFRY2QpYpeuuaZIYO3BG_nX3cPGRaQ20wYpnVBQpdf_b2MUoxC7fpCRgTHa6xXH4tq1iLN_VHMXXYMmTh5OAXiRUjj2-6uGuG6vBQurSFiZ5DeJhmYcFMwwGyaopFw6JtD5Bir8NNmXfOTJ7gdlg5W-52__dcft-tM11/p.jpeg',
--   GETUTCDATE(),
--   'both',
--   0,
--   1,
--   4,
--   '1',
--   1,
--   1,
--   'assadara schools graduation'
-- )
-- -- add more rows here
-- GO

-- ALTER TABLE [dbo].[articles] DROP COLUMN [articleTitle]
-- ALTER TABLE [dbo].[articles] ADD [articleTitleAr] [nvarchar](100) NOT NULL
-- ALTER TABLE [dbo].[articles] ADD [articleTitleEn] [nvarchar](100) NOT NULL

-- ALTER TABLE [dbo].[articles] DROP COLUMN [articleText]
-- ALTER TABLE [dbo].[articles] ADD [articleTextAr] [nvarchar](max) NOT NULL
-- ALTER TABLE [dbo].[articles] ADD [articleTextEn] [nvarchar](max) NOT NULL

-- ALTER TABLE [dbo].[articles] DROP COLUMN [authorName]
-- ALTER TABLE [dbo].[articles] ADD [authorNameAr] [nvarchar](100) NOT NULL
-- ALTER TABLE [dbo].[articles] ADD [authorNameEn] [nvarchar](100) NOT NULL

-- SELECT * FROM [dbo].[articles]

-- fields meaning
-- =================
-- [schoolId], [stageId], [forCompany] reflects artical dependency
-- [displayAlsoAt] reflects other contexts to be displayed at in addition to its original context

-- add 3 relations [employeesJobs - departments - schools]
----------------------------------------------------------

-- ALTER TABLE [dbo].[articles] DROP CONSTRAINT [FK_employeesJobs_articles]
-- ALTER TABLE [dbo].[articles]
-- ADD CONSTRAINT [FK_employeesJobs_articles] FOREIGN KEY([empJobId])
-- REFERENCES [dbo].[employeesJobs] ([empJobId])
-- ON UPDATE CASCADE
-- ON DELETE SET NULL
-- GO

-- ALTER TABLE [dbo].[articles] DROP CONSTRAINT [FK_departments_articles]
-- ALTER TABLE [dbo].[articles]
-- ADD CONSTRAINT [FK_departments_articles] FOREIGN KEY([stageId])
-- REFERENCES [dbo].[departments] ([departmentId])
-- ON UPDATE CASCADE
-- ON DELETE SET NULL
-- GO

-- ALTER TABLE [dbo].[articles] DROP CONSTRAINT [FK_schools_articles]
-- ALTER TABLE [dbo].[articles]
-- ADD CONSTRAINT [FK_schools_articles] FOREIGN KEY([schoolId])
-- REFERENCES [dbo].[schools] ([schoolId])
-- ON UPDATE CASCADE
-- ON DELETE SET NULL
-- GO

-----------------------------------------------------------------------------

-- CREATE TABLE [dbo].[albums] (
-- 	[albumId] [int] identity(1,1) PRIMARY KEY,
-- 	[albumTitleAr] [nvarchar](100) NOT NULL,
--   [albumTitleEn] [nvarchar](100) NOT NULL,
--   [descriptionAr] [nvarchar](max) NULL,
--   [descriptionEn] [nvarchar](max) NULL,
--   [albumDate] [smalldatetime] NOT NULL,
--   [keywords] [nvarchar](max) NULL,
--   [displayAlsoAt] [varchar](10) NOT NULL,
--   [approved] [bit] NOT NULL,
--   [enabled] [bit] NOT NULL,
--   [forCompany] [bit] NOT NULL,
--   [schoolId] [tinyint] NULL,
-- 	 [stageId] [tinyint] NULL,
--   [empJobId] [int] NULL,
--   [categoryId] [tinyint] NULL,
-- )
-- GO

-- Insert rows into table '[dbo].[albums]'
-- INSERT INTO [dbo].[albums]
-- ( -- columns to insert data into
--  [albumTitleAr], [albumTitleEn], [descriptionAr], [descriptionEn],
--  [albumDate], [displayAlsoAt], [forCompany], [approved], [enabled], [categoryId]
-- )
-- VALUES
-- ( -- values for the columns in the list above
--  'ألبوم الصفحة الرئيسية', 'Hero Slider', 'الألبوم الذي يعرض في أول الصفحة الرئيسية', 'The home page Hero Slider',
--  GETUTCDATE(), 'company', 1, 1, 1, 6
-- )
-- GO

-- SELECT * from [dbo].[albums]

-- add 4 relations [employeesJobs - departments - schools - mediaCategories]
----------------------------------------------------------------------------

-- ALTER TABLE [dbo].[albums] DROP CONSTRAINT [FK_employeesJobs_albums]
-- ALTER TABLE [dbo].[albums]
-- ADD CONSTRAINT [FK_employeesJobs_albums] FOREIGN KEY([empJobId])
-- REFERENCES [dbo].[employeesJobs] ([empJobId])
-- ON UPDATE CASCADE
-- ON DELETE SET NULL
-- GO

-- ALTER TABLE [dbo].[albums] DROP CONSTRAINT [FK_departments_albums]
-- ALTER TABLE [dbo].[albums]
-- ADD CONSTRAINT [FK_departments_albums] FOREIGN KEY([stageId])
-- REFERENCES [dbo].[departments] ([departmentId])
-- ON UPDATE CASCADE
-- ON DELETE SET NULL
-- GO

-- ALTER TABLE [dbo].[albums] DROP CONSTRAINT [FK_schools_albums]
-- ALTER TABLE [dbo].[albums]
-- ADD CONSTRAINT [FK_schools_albums] FOREIGN KEY([schoolId])
-- REFERENCES [dbo].[schools] ([schoolId])
-- ON UPDATE CASCADE
-- ON DELETE SET NULL
-- GO

-- ALTER TABLE [dbo].[albums] DROP CONSTRAINT [FK_mediaCategories_albums]
-- ALTER TABLE [dbo].[albums]
-- ADD CONSTRAINT [FK_mediaCategories_albums] FOREIGN KEY([categoryId])
-- REFERENCES [dbo].[mediaCategories] ([categoryId])
-- ON UPDATE CASCADE
-- ON DELETE SET NULL
-- GO

-------------------------------------------------------------------------------------
-- CREATE TABLE [dbo].[photos] (
-- 	[photoId] [int] identity(1,1) PRIMARY KEY,
-- 	[photoTitleAr] [nvarchar](100) NOT NULL,
--   [photoTitleEn] [nvarchar](100) NOT NULL,
--   [descriptionAr] [nvarchar](max) NULL,
--   [descriptionEn] [nvarchar](max) NULL,
--   [photoURL] [varchar](max) NOT NULL,
--   [thumbURL] [varchar](max) NOT NULL,
--   [moreURL] [varchar](max) NULL,
--   [photoDate] [smalldatetime] NOT NULL,
--   [approved] [bit] NOT NULL,
--   [enabled] [bit] NOT NULL,
--   [empJobId] [int] NULL,
--   [albumId] [int] NULL,
-- )
-- GO

-- Insert rows into table '[dbo].[photos]'
-- INSERT INTO [dbo].[photos]
-- ( -- columns to insert data into
--  [photoTitleAr],
--  [photoTitleEn],
--  [descriptionAr],
--  [descriptionEn],
--  [photoURL],
--  [thumbURL],
--  [photoDate], [approved], [enabled], [albumId]
-- )
-- VALUES
-- ( -- values for the columns in the list above
--  'حفل خريجي مدارس الصدارة',
--  'Assadarah Graduation Party',
--  'تكريم خريجي مدارس الصدارة الدفعة السابعة',
--  'Honoring Assadarah Graduates for Intake 7',
--  'https://previews.dropbox.com/p/thumb/AAY8d1Wp3yFGvsljOWZTXoxG8G9tTGcqRVDTLhiOrIvgKabxhBBXqMbiPOmaRbifjIpqt8WzueGnThvJJSKSd6wS34wMn1hV6DLGX60MknIzuz-qyy9I9R9FEDZm3EVGHud85bEQdxaL-FIkUvO_kTmNCWrMVeRcrIbKC5fQM0EhdkouK-LkeFRY2QpYpeuuaZIYO3BG_nX3cPGRaQ20wYpnVBQpdf_b2MUoxC7fpCRgTHa6xXH4tq1iLN_VHMXXYMmTh5OAXiRUjj2-6uGuG6vBQurSFiZ5DeJhmYcFMwwGyaopFw6JtD5Bir8NNmXfOTJ7gdlg5W-52__dcft-tM11/p.jpeg',
--  'https://previews.dropbox.com/p/thumb/AAY8d1Wp3yFGvsljOWZTXoxG8G9tTGcqRVDTLhiOrIvgKabxhBBXqMbiPOmaRbifjIpqt8WzueGnThvJJSKSd6wS34wMn1hV6DLGX60MknIzuz-qyy9I9R9FEDZm3EVGHud85bEQdxaL-FIkUvO_kTmNCWrMVeRcrIbKC5fQM0EhdkouK-LkeFRY2QpYpeuuaZIYO3BG_nX3cPGRaQ20wYpnVBQpdf_b2MUoxC7fpCRgTHa6xXH4tq1iLN_VHMXXYMmTh5OAXiRUjj2-6uGuG6vBQurSFiZ5DeJhmYcFMwwGyaopFw6JtD5Bir8NNmXfOTJ7gdlg5W-52__dcft-tM11/p.jpeg',
--  GETUTCDATE(), 1, 1, 1
-- ),
-- ( -- values for the columns in the list above
--  'الزيارات الخارجية',
--  'Outer Visit',
--  'زيارة طلاب ابتدائية الصدارة إلي مشكاه',
--  'Assadarah Primary stage students visit to Mishkah',
--  'https://previews.dropbox.com/p/thumb/AAYE6RSrWVql4kJe6ZbQMAtQRZxU4KamNkVrn-PuuF12KnSl-5y_qPRA3Eh_nePZpwsH-qHwuf2yLWdBpI701eTuV5iJkVM_vbZp9ynt2Lm1T_MhrXEuscoP1yZTuuBqvnVskiXwdExB4LsgTNfswlaEa4BqnQyqFCNvAsxiCp-sqCTzhJR3Ms1x2E5ekbbGrpfoqw72FbHQP_sRSbCUTIAdzvkQvnK9kReR4EYV7bMH82zHQcE9o4zm7MDpjFOBT6tzT2muBWHRjJh8cPwSYZolONYKPA36XzbfyRPgk3uQ72trcvAyl67_f5DFHIgB8GHjxo7TRiN4ORSRMGKWHlpT/p.jpeg',
--  'https://previews.dropbox.com/p/thumb/AAYE6RSrWVql4kJe6ZbQMAtQRZxU4KamNkVrn-PuuF12KnSl-5y_qPRA3Eh_nePZpwsH-qHwuf2yLWdBpI701eTuV5iJkVM_vbZp9ynt2Lm1T_MhrXEuscoP1yZTuuBqvnVskiXwdExB4LsgTNfswlaEa4BqnQyqFCNvAsxiCp-sqCTzhJR3Ms1x2E5ekbbGrpfoqw72FbHQP_sRSbCUTIAdzvkQvnK9kReR4EYV7bMH82zHQcE9o4zm7MDpjFOBT6tzT2muBWHRjJh8cPwSYZolONYKPA36XzbfyRPgk3uQ72trcvAyl67_f5DFHIgB8GHjxo7TRiN4ORSRMGKWHlpT/p.jpeg',
--  GETUTCDATE(), 1, 1, 1
-- ),
-- ( -- values for the columns in the list above
--  'المسابقات المحلية',
--  'Local Competitions',
--  'مشاركة طلاب ثانوية الصدارة في ماراثون الرياضيات',
--  'Assadarah Secondary stage students participate in Math Marathon ',
--  'https://previews.dropbox.com/p/thumb/AAaxuQCFfZD2_9Ea_P7jldQ-4PhpRkcjyWhdG8Ucn1kHstdoXkDSxHc2hDNhHH6ssNgXbqAXF96V38GoCrTNBa4-eqc2JYFgneghvuvACs2SlJA_xuu3SfNjBugsSZEf3OSUOuCHBeIfgiouAXblbbqeaqXYhDZcEVKIRonbP6qRyzc_j3aYYKoCd9pF8IopUa5qujiQzSccDtrF9TnW8OX2uNsoqcXjVNx0e1Dg2nUEhZrYahgGYmoeQ4zdIGozqCJDfI8Wfw0WIGjDf5XDcG7HIPxLsYQ1ASuYcwlcMQ8KhfVnWYmntL6Jzg2eN2UmbtC33alobk8EehevyRZaEiym/p.jpeg',
--  'https://previews.dropbox.com/p/thumb/AAaxuQCFfZD2_9Ea_P7jldQ-4PhpRkcjyWhdG8Ucn1kHstdoXkDSxHc2hDNhHH6ssNgXbqAXF96V38GoCrTNBa4-eqc2JYFgneghvuvACs2SlJA_xuu3SfNjBugsSZEf3OSUOuCHBeIfgiouAXblbbqeaqXYhDZcEVKIRonbP6qRyzc_j3aYYKoCd9pF8IopUa5qujiQzSccDtrF9TnW8OX2uNsoqcXjVNx0e1Dg2nUEhZrYahgGYmoeQ4zdIGozqCJDfI8Wfw0WIGjDf5XDcG7HIPxLsYQ1ASuYcwlcMQ8KhfVnWYmntL6Jzg2eN2UmbtC33alobk8EehevyRZaEiym/p.jpeg',
--  GETUTCDATE(), 1, 1, 1
-- ),
-- ( -- values for the columns in the list above
--  'مصادر التعليم',
--  'Learning Resources',
--  'حث الطلاب على الاطلاع والقراءة واستخدام مصادر المعرفة',
--  'Urging student to look for knowledge through Reading and Other Information resources',
--  'https://previews.dropbox.com/p/thumb/AAb4IKmnaLPAwYHjGo8sgoFpuAclY_1BT-HAzuivKhR7Nezjc74WxRLIdQPBuxJ2y4lw4044fu_l558beC0b0DDxu83XHK3OS0cH1J4rCC8oyONKLUZIYKvUX7Sv8BX1scbJ6otU-nCdbC883gaBUdrO0wHIuRjXUIL_vFlIuJeCUfx-MzJJ_pcfkL45gRBi-vG7fS_SFxPKvETKIEtfPGVJDKj6aUEelKBxaGWsABjRRQEyuTFIIxd26Ilh8F3bYv2f7FwJAqshwqkjTiHv50AYjHYMKLc9m-uCjGjqyIyQcLaRzPEaM9Z-5YN5XxhDn8LXMZQkiMwjah3b_ciJPQ3j/p.jpeg',
--  'https://previews.dropbox.com/p/thumb/AAb4IKmnaLPAwYHjGo8sgoFpuAclY_1BT-HAzuivKhR7Nezjc74WxRLIdQPBuxJ2y4lw4044fu_l558beC0b0DDxu83XHK3OS0cH1J4rCC8oyONKLUZIYKvUX7Sv8BX1scbJ6otU-nCdbC883gaBUdrO0wHIuRjXUIL_vFlIuJeCUfx-MzJJ_pcfkL45gRBi-vG7fS_SFxPKvETKIEtfPGVJDKj6aUEelKBxaGWsABjRRQEyuTFIIxd26Ilh8F3bYv2f7FwJAqshwqkjTiHv50AYjHYMKLc9m-uCjGjqyIyQcLaRzPEaM9Z-5YN5XxhDn8LXMZQkiMwjah3b_ciJPQ3j/p.jpeg',
--  GETUTCDATE(), 1, 1, 1
-- ),
-- ( -- values for the columns in the list above
--  'الملاعب والصالات',
--  'Playgrounds, Gyms and activity rooms',
--  'ملاعب كرة القدم والسلة والطائرة وحمام السباحة وصالة اللياقة',
--  'Playgrounds for football, vollyball and basektball. Swimming pool and Gym',
--  'https://previews.dropbox.com/p/thumb/AAaCqqDD8Ro5zi3uJuDqNK9OHT9PUw343RPGwBkdWe4fRtgFNzuYYnMa7DQ0UiFLL3f0YGboi7NizVVFSPYhH0eJA4LB_O6puCtgTu33C2tImvgyzSjokGQxEGbeEY9nYdf_XmuuRbDyNyrS2IVZqUX6D-L8E2G9mCOPkPgYZLDyg6k50Vzu3Vkl-w5NhExyovvUbS7tlCVSagBtnqKh_pN-IPIejSpyvQ7NgkHFIp66zQMRsGaMphVYoIN4qr-htYlcrcJEtChk_1JDOf9vkWWF_lGwi6oD0qTMmWRy1eHXGrc4gIdGGG7Wr7b1-Xujml0CN8KVfqz_Aax_dSWTw8vr/p.jpeg',
--  'https://previews.dropbox.com/p/thumb/AAaCqqDD8Ro5zi3uJuDqNK9OHT9PUw343RPGwBkdWe4fRtgFNzuYYnMa7DQ0UiFLL3f0YGboi7NizVVFSPYhH0eJA4LB_O6puCtgTu33C2tImvgyzSjokGQxEGbeEY9nYdf_XmuuRbDyNyrS2IVZqUX6D-L8E2G9mCOPkPgYZLDyg6k50Vzu3Vkl-w5NhExyovvUbS7tlCVSagBtnqKh_pN-IPIejSpyvQ7NgkHFIp66zQMRsGaMphVYoIN4qr-htYlcrcJEtChk_1JDOf9vkWWF_lGwi6oD0qTMmWRy1eHXGrc4gIdGGG7Wr7b1-Xujml0CN8KVfqz_Aax_dSWTw8vr/p.jpeg',
--  GETUTCDATE(), 1, 1, 1
-- ),
-- ( -- values for the columns in the list above
--  'الإنجازات والجوائز',
--  'Trophies',
--  'يشارك طلابنا في العديد من المسابقات والمنافسات المحلية والدولية ويحصلون على العديد من المراكز المتقدمة والجوائز',
--  'Our students participate in national and international competitions and get a lot of prizes and advanced positions',
--  'https://previews.dropbox.com/p/thumb/AAaMIwLQRi9mhFUfedYjLcPQaxqUF6rZtfVbm62kubT81i2JigsyDC4QEUiVStZ1hZkesilZBsUFQ-6QEr_-22Q6LYnQAUc4KmSBu711lhjjcP_Ctmu914wH82UpPRFhHae51ggJEx8i6_fk3pQNb6U0G5Kg-Rg1Kv2VZsBn9kRAS2W899OmTIEJd1yozNVBJeqiTctgLLb8dKpWlh31fBVqMQp13XauJAoiM_IPHKhYfyNNFUSO9DMk0iUM2NE874P8KkAK9aCN1CoDvvV_kq_RPvRBRdG4fnphRwME2XpYRE6J2JZqONsd6pMTOh7QcHX7GUxYlHzBd1qfuTqa079b/p.jpeg',
--  'https://previews.dropbox.com/p/thumb/AAaMIwLQRi9mhFUfedYjLcPQaxqUF6rZtfVbm62kubT81i2JigsyDC4QEUiVStZ1hZkesilZBsUFQ-6QEr_-22Q6LYnQAUc4KmSBu711lhjjcP_Ctmu914wH82UpPRFhHae51ggJEx8i6_fk3pQNb6U0G5Kg-Rg1Kv2VZsBn9kRAS2W899OmTIEJd1yozNVBJeqiTctgLLb8dKpWlh31fBVqMQp13XauJAoiM_IPHKhYfyNNFUSO9DMk0iUM2NE874P8KkAK9aCN1CoDvvV_kq_RPvRBRdG4fnphRwME2XpYRE6J2JZqONsd6pMTOh7QcHX7GUxYlHzBd1qfuTqa079b/p.jpeg',
--  GETUTCDATE(), 1, 1, 1
-- )
-- GO

-- SELECT * from [dbo].[photos]

-- insert photos instructions
------------------------------
-- inset photo in table
-- generate photo name before save it in host: [albumId]_[photoId]_[photo|thumb]
-- save it to host
-- update the photoURL & thumbURL

-- add 2 relations [employeesJobs - albums]
----------------------------------------------------------------------------

-- ALTER TABLE [dbo].[photos] DROP CONSTRAINT [FK_employeesJobs_photos]
-- ALTER TABLE [dbo].[photos]
-- ADD CONSTRAINT [FK_employeesJobs_photos] FOREIGN KEY([empJobId])
-- REFERENCES [dbo].[employeesJobs] ([empJobId])
-- ON UPDATE CASCADE
-- ON DELETE SET NULL
-- GO

-- ALTER TABLE [dbo].[photos] DROP CONSTRAINT [FK_albums_photos]
-- ALTER TABLE [dbo].[photos]
-- ADD CONSTRAINT [FK_albums_photos] FOREIGN KEY([albumId])
-- REFERENCES [dbo].[albums] ([albumId])
-- ON UPDATE NO ACTION
-- ON DELETE NO ACTION
-- GO

-------------------------------------------------------------------------------------------

-- List columns in all tables whose name is like 'articles'
-- SELECT
--   TableName = tbl.TABLE_SCHEMA + '.' + tbl.TABLE_NAME,
--   ColumnName = col.COLUMN_NAME,
--   DataType = col.DATA_TYPE,
--   [IsNull] = col.IS_NULLABLE
-- FROM INFORMATION_SCHEMA.TABLES tbl
-- INNER JOIN INFORMATION_SCHEMA.COLUMNS col
--   ON col.TABLE_NAME = tbl.TABLE_NAME
--   AND col.TABLE_SCHEMA = tbl.TABLE_SCHEMA
-- WHERE tbl.TABLE_TYPE = 'BASE TABLE' and tbl.TABLE_NAME = 'articles'
-- GO

-- SELECT
--   TableName = tbl.TABLE_SCHEMA + '.' + tbl.TABLE_NAME,
--   ColumnName = col.COLUMN_NAME,
--   DataType = col.DATA_TYPE,
--   [IsNull] = col.IS_NULLABLE
-- FROM INFORMATION_SCHEMA.TABLES tbl
-- INNER JOIN INFORMATION_SCHEMA.COLUMNS col
--   ON col.TABLE_NAME = tbl.TABLE_NAME
--   AND col.TABLE_SCHEMA = tbl.TABLE_SCHEMA
-- WHERE tbl.TABLE_TYPE = 'BASE TABLE' and col.COLUMN_NAME = 'stageId'
-- GO

-- sp_fkeys 'stages'
---------------------
-- FK_grades_stages
-- FK_schoolDayEvents_stages

-- Add a new column 'isStage' to table 'departments' in schema 'dbo'
-- ALTER TABLE dbo.departments ADD isStage [bit] NOT NULL DEFAULT(0)
-- GO

-- replace the relation between grades and stages with one between grades and departments
-- ALTER TABLE [dbo].[grades] DROP CONSTRAINT [FK_grades_stages]
-- GO
-- ALTER TABLE [dbo].[grades]
-- ADD CONSTRAINT [FK_departments_grades] FOREIGN KEY([stageId])
-- REFERENCES [dbo].[departments] ([departmentId])
-- ON UPDATE NO ACTION
-- ON DELETE NO ACTION
-- GO

-- replace the relation between schoolDayEvents and stages with one between schoolDayEvents and departments
-- ALTER TABLE [dbo].[schoolDayEvents] DROP CONSTRAINT [FK_schoolDayEvents_stages]
-- GO
-- ALTER TABLE [dbo].[schoolDayEvents]
-- ADD CONSTRAINT [FK_departments_schoolDayEvents] FOREIGN KEY([stageId])
-- REFERENCES [dbo].[departments] ([departmentId])
-- ON UPDATE NO ACTION
-- ON DELETE NO ACTION
-- GO

-- delete the stages table
-- DROP TABLE [stages]

-- ALTER TABLE [dbo].[departments] ADD [branchId] [tinyint] NULL
-- ALTER TABLE [dbo].[departments]
-- ADD CONSTRAINT [FK_branches_departments] FOREIGN KEY([branchId])
-- REFERENCES [dbo].[branches] ([branchId])
-- ON UPDATE NO ACTION
-- ON DELETE NO ACTION
-- GO

-- DELETE FROM [dbo].[departments]
-- DELETE FROM [dbo].[grades]
-- DELETE FROM [dbo].[schoolDayEvents]

-- SELECT * from [dbo].[mediaCategories]
-- sp_fkeys 'employeesJobs'


-- SELECT * FROM [dbo].[branches]
-- SELECT * FROM [dbo].[stages]
-- GO
-- SELECT * FROM [dbo].[schools]
-- GO

-- Select rows from a Table or View 'TableOrViewName' in schema 'SchemaName'
-- insert into departments
-- ([departmentId], [departmentNameAr], [departmentNameEn], [isDeleted], [issuerId], [isStage], [branchId])
-- values
-- (1, 'ابتدائي', 'Primary', 0, '1122112211', 1, 1),
-- (2, 'متوسط', 'Intermediate', 0, '1122112211', 1, 1),
-- (3, 'ثانوي', 'Secondary', 0, '1122112211', 1, 1)

-- insert into departments
-- ([departmentId], [departmentNameAr], [departmentNameEn], [isDeleted], [issuerId], [isStage], [branchId])
-- values
-- (4, 'رياض أطفال', 'Kindergarten', 0, '1122112211', 1, 2),
-- (5, 'ابتدائي', 'Primary', 0, '1122112211', 1, 2),
-- (6, 'متوسط', 'Intermediate', 0, '1122112211', 1, 2),
-- (7, 'ثانوي', 'Secondary', 0, '1122112211', 1, 2)

-- Select rows from a Table or View 'departments' in schema 'SchemaName'
-- SELECT * FROM [dbo].[articles]
-- GO

-- SELECT TOP (3) * FROM [dbo].[articles] WHERE categoryIds like '%1%' ORDER BY articleId DESC
-- SELECT * FROM [dbo].[articles]

-- SELECT * FROM [dbo].[photos]
-- SELECT * FROM [dbo].[abouts]
-- SELECT * FROM [dbo].[articles]

-- Update rows in table '[dbo].[photos]'
---------------------------------------
-- UPDATE [dbo].[photos]
-- SET
--   [photoURL] = 'https://i.ibb.co/HVy83Qn/01.jpg',
--   [thumbURL] = 'https://i.ibb.co/HVy83Qn/01.jpg'
-- WHERE photoId = 1
-- GO
-- UPDATE [dbo].[photos]
-- SET
--   [photoURL] = 'https://i.ibb.co/YZpzy97/02.jpg',
--   [thumbURL] = 'https://i.ibb.co/YZpzy97/02.jpg'
-- WHERE photoId = 2
-- GO
-- UPDATE [dbo].[photos]
-- SET
--   [photoURL] = 'https://i.ibb.co/YR9VQVG/03.jpg',
--   [thumbURL] = 'https://i.ibb.co/YR9VQVG/03.jpg'
-- WHERE photoId = 3
-- GO
-- UPDATE [dbo].[photos]
-- SET
--   [photoURL] = 'https://i.ibb.co/St5dpL6/04.jpg',
--   [thumbURL] = 'https://i.ibb.co/St5dpL6/04.jpg'
-- WHERE photoId = 4
-- GO
-- UPDATE [dbo].[photos]
-- SET
--   [photoURL] = 'https://i.ibb.co/wzZ1DN1/05.jpg',
--   [thumbURL] = 'https://i.ibb.co/wzZ1DN1/05.jpg'
-- WHERE photoId = 5
-- GO
-- UPDATE [dbo].[photos]
-- SET
--   [photoURL] = 'https://i.ibb.co/hmjpvwW/06.jpg',
--   [thumbURL] = 'https://i.ibb.co/hmjpvwW/06.jpg'
-- WHERE photoId = 6
-- GO

-- Update rows in table 'abouts'
-- UPDATE [dbo].[abouts]
-- SET [videoURL] = 'https://www.youtube.com/watch?v=ZoNgUKLW4TQ'
-- WHERE [aboutId] = 1
-- GO

-- Update rows in table '[dbo].[abouts]'
---------------------------------------
-- UPDATE [dbo].[abouts]
-- SET [photoURL] = 'https://i.ibb.co/HVy83Qn/01.jpg'
-- WHERE aboutId = 1
-- GO
-- UPDATE [dbo].[abouts]
-- SET [photoURL] = 'https://i.ibb.co/YZpzy97/02.jpg'
-- WHERE aboutId = 2
-- GO
-- UPDATE [dbo].[abouts]
-- SET [photoURL] = 'https://i.ibb.co/YR9VQVG/03.jpg'
-- WHERE aboutId = 3
-- GO
-- UPDATE [dbo].[abouts]
-- SET [photoURL] = 'https://i.ibb.co/St5dpL6/04.jpg'
-- WHERE aboutId = 4
-- GO
-- UPDATE [dbo].[abouts]
-- SET [photoURL] = 'https://i.ibb.co/wzZ1DN1/05.jpg'
-- WHERE aboutId = 5
-- GO
-- UPDATE [dbo].[abouts]
-- SET [photoURL] = 'https://i.ibb.co/ZKT7wyb/ceo.jpg'
-- WHERE aboutId = 6
-- GO

-- Update rows in table '[dbo].[articles]'
---------------------------------------
-- UPDATE [dbo].[articles]
-- SET [mainPhotoURL] = 'https://i.ibb.co/HVy83Qn/01.jpg'
-- WHERE articleId = 4
-- GO
-- UPDATE [dbo].[articles]
-- SET [mainPhotoURL] = 'https://i.ibb.co/YZpzy97/02.jpg'
-- WHERE articleId = 5
-- GO
-- UPDATE [dbo].[articles]
-- SET [mainPhotoURL] = 'https://i.ibb.co/YR9VQVG/03.jpg'
-- WHERE articleId = 6
-- GO
-- UPDATE [dbo].[articles]
-- SET [mainPhotoURL] = 'https://i.ibb.co/St5dpL6/04.jpg'
-- WHERE articleId = 7
-- GO
-- UPDATE [dbo].[articles]
-- SET [mainPhotoURL] = 'https://i.ibb.co/wzZ1DN1/05.jpg'
-- WHERE articleId = 8
-- GO
