-- drop all tables constrains
-----------------------------
ALTER TABLE [assadara_ssms_admin].[lessonsFiles] DROP CONSTRAINT [FK_lessonsFiles_docTypes];
ALTER TABLE [assadara_ssms_admin].[lessonsFiles] DROP CONSTRAINT [FK_lessonsFiles_lessons];
ALTER TABLE [assadara_ssms_admin].[subjects] DROP CONSTRAINT [FK_subjects_majors];
ALTER TABLE [assadara_ssms_admin].[branches] DROP CONSTRAINT [FK_branches_schools];
ALTER TABLE [assadara_ssms_admin].[users] DROP CONSTRAINT [FK_users_accountStatus];
ALTER TABLE [assadara_ssms_admin].[users] DROP CONSTRAINT [FK_users_userTypes];
ALTER TABLE [assadara_ssms_admin].[academicWeeks] DROP CONSTRAINT [FK_academicWeeks_academicSemesters];
ALTER TABLE [assadara_ssms_admin].[stages] DROP CONSTRAINT [FK_stages_branches];
ALTER TABLE [assadara_ssms_admin].[employees] DROP CONSTRAINT [FK_employees_countries];
ALTER TABLE [assadara_ssms_admin].[employees] DROP CONSTRAINT [FK_employees_users];
ALTER TABLE [assadara_ssms_admin].[parents] DROP CONSTRAINT [FK_parents_countries];
ALTER TABLE [assadara_ssms_admin].[parents] DROP CONSTRAINT [FK_parents_users];
ALTER TABLE [assadara_ssms_admin].[refreshTokens] DROP CONSTRAINT [FK_users_refreshTokens];
ALTER TABLE [assadara_ssms_admin].[usersDocs] DROP CONSTRAINT [FK_usersDocs_docTypes];
ALTER TABLE [assadara_ssms_admin].[usersDocs] DROP CONSTRAINT [FK_usersDocs_users];
ALTER TABLE [assadara_ssms_admin].[verificationCodes] DROP CONSTRAINT [FK_verificationCodeTypes_verificationCodes];
ALTER TABLE [assadara_ssms_admin].[verificationCodes] DROP CONSTRAINT [FK_users_verificationCodes];
ALTER TABLE [assadara_ssms_admin].[grades] DROP CONSTRAINT [FK_grades_stages];
ALTER TABLE [assadara_ssms_admin].[schoolDayEvents] DROP CONSTRAINT [FK_schoolDayEvents_stages];
ALTER TABLE [assadara_ssms_admin].[employeesFinance] DROP CONSTRAINT [FK_employeesFinance_employees];
ALTER TABLE [assadara_ssms_admin].[employeesHR] DROP CONSTRAINT [FK_EmployeesHR_employees];
ALTER TABLE [assadara_ssms_admin].[employeesJobs] DROP CONSTRAINT [FK_employeesJobs_departments];
ALTER TABLE [assadara_ssms_admin].[employeesJobs] DROP CONSTRAINT [FK_employeesJobs_employees];
ALTER TABLE [assadara_ssms_admin].[employeesJobs] DROP CONSTRAINT [FK_employeesJobs_jobs];
ALTER TABLE [assadara_ssms_admin].[students] DROP CONSTRAINT [FK_students_countries];
ALTER TABLE [assadara_ssms_admin].[students] DROP CONSTRAINT [FK_students_parents];
ALTER TABLE [assadara_ssms_admin].[students] DROP CONSTRAINT [FK_students_users];
ALTER TABLE [assadara_ssms_admin].[classrooms] DROP CONSTRAINT [FK_classrooms_grades];
ALTER TABLE [assadara_ssms_admin].[gradesSubjects] DROP CONSTRAINT [FK_gradesSubjects_grades];
ALTER TABLE [assadara_ssms_admin].[gradesSubjects] DROP CONSTRAINT [FK_gradesSubjects_subjects];
ALTER TABLE [assadara_ssms_admin].[employeesActions] DROP CONSTRAINT [FK_employeesActions_actions];
ALTER TABLE [assadara_ssms_admin].[employeesActions] DROP CONSTRAINT [FK_employeesActions_employeesJobs];
ALTER TABLE [assadara_ssms_admin].[teachersQuorums] DROP CONSTRAINT [FK_teachersQuorums_employeesJobs];
ALTER TABLE [assadara_ssms_admin].[teachersQuorums] DROP CONSTRAINT [FK_teachersQuorums_academicSemesters];
ALTER TABLE [assadara_ssms_admin].[studentsViolations] DROP CONSTRAINT [FK_studentsViolations_employeesJobs];
ALTER TABLE [assadara_ssms_admin].[studentsViolations] DROP CONSTRAINT [FK_studentsViolations_students];
ALTER TABLE [assadara_ssms_admin].[studentsViolations] DROP CONSTRAINT [FK_studentsViolations_behavioralViolations];
ALTER TABLE [assadara_ssms_admin].[classesStudents] DROP CONSTRAINT [FK_classesStudents_classrooms];
ALTER TABLE [assadara_ssms_admin].[classesStudents] DROP CONSTRAINT [FK_classesStudents_students];
ALTER TABLE [assadara_ssms_admin].[classesStudents] DROP CONSTRAINT [FK_classesStudents_academicYears];
ALTER TABLE [assadara_ssms_admin].[periods] DROP CONSTRAINT [FK_periods_classrooms];
ALTER TABLE [assadara_ssms_admin].[periods] DROP CONSTRAINT [FK_periods_employeesJobs];
ALTER TABLE [assadara_ssms_admin].[periods] DROP CONSTRAINT [FK_periods_gradesSubjects];
ALTER TABLE [assadara_ssms_admin].[periods] DROP CONSTRAINT [FK_periods_schoolDayEvents];
ALTER TABLE [assadara_ssms_admin].[periods] DROP CONSTRAINT [FK_periods_academicSemesters];
ALTER TABLE [assadara_ssms_admin].[timeTables] DROP CONSTRAINT [FK_timeTable_employeesJobs];
ALTER TABLE [assadara_ssms_admin].[timeTables] DROP CONSTRAINT [FK_timeTable_gradesSubjects];
ALTER TABLE [assadara_ssms_admin].[timeTables] DROP CONSTRAINT [FK_timeTable_schoolDayEvents];
ALTER TABLE [assadara_ssms_admin].[studentsProcedures] DROP CONSTRAINT [FK_studentsProcedures_employeesJobs];
ALTER TABLE [assadara_ssms_admin].[studentsProcedures] DROP CONSTRAINT [FK_studentsProcedures_remedialProcedures];
ALTER TABLE [assadara_ssms_admin].[studentsProcedures] DROP CONSTRAINT [FK_studentsProcedures_studentsViolations];
ALTER TABLE [assadara_ssms_admin].[periodsDetails] DROP CONSTRAINT [FK_periodsDetails_periods];
ALTER TABLE [assadara_ssms_admin].[periodsDetails] DROP CONSTRAINT [FK_periodsDetails_students];
ALTER TABLE [assadara_ssms_admin].[periodsFiles] DROP CONSTRAINT [FK_periodsFiles_docTypes];
ALTER TABLE [assadara_ssms_admin].[periodsFiles] DROP CONSTRAINT [FK_periodsFiles_weeksPlans];
ALTER TABLE [assadara_ssms_admin].[weeksPlans] DROP CONSTRAINT [FK_weeksPlans_lessons];
ALTER TABLE [assadara_ssms_admin].[weeksPlans] DROP CONSTRAINT [FK_weeksPlans_timeTable];
ALTER TABLE [assadara_ssms_admin].[weeksPlans] DROP CONSTRAINT [FK_weeksPlans_academicWeeks];
ALTER TABLE [assadara_ssms_admin].[teachersEdu] DROP CONSTRAINT [FK_teachersEdu_employeesJobs];
ALTER TABLE [assadara_ssms_admin].[teachersEdu] DROP CONSTRAINT [FK_teachersEdu_gradesSubjects];
ALTER TABLE [assadara_ssms_admin].[academicSemesters] DROP CONSTRAINT [FK_academicSemesters_academicYears];
ALTER TABLE [assadara_ssms_admin].[jobsActions] DROP CONSTRAINT [FK_jobsActions_actions];
ALTER TABLE [assadara_ssms_admin].[jobsActions] DROP CONSTRAINT [FK_jobsActions_jobs];
ALTER TABLE [assadara_ssms_admin].[lessonsFiles] DROP CONSTRAINT [PK_lessonsFiles];
ALTER TABLE [assadara_ssms_admin].[jobsActions] DROP CONSTRAINT [PK_jobsActions];
ALTER TABLE [assadara_ssms_admin].[timeTables] DROP CONSTRAINT [PK_timeTables];
ALTER TABLE [assadara_ssms_admin].[docTypes] DROP CONSTRAINT [PK_docTypes];
ALTER TABLE [assadara_ssms_admin].[jobs] DROP CONSTRAINT [PK_jobs];
ALTER TABLE [assadara_ssms_admin].[lessons] DROP CONSTRAINT [PK_lessons];
ALTER TABLE [assadara_ssms_admin].[periodsFiles] DROP CONSTRAINT [PK_periodsFiles];
ALTER TABLE [assadara_ssms_admin].[majors] DROP CONSTRAINT [PK_majors];
ALTER TABLE [assadara_ssms_admin].[remedialProcedures] DROP CONSTRAINT [PK_remedialProcedures];
ALTER TABLE [assadara_ssms_admin].[schools] DROP CONSTRAINT [PK_schools];
ALTER TABLE [assadara_ssms_admin].[userTypes] DROP CONSTRAINT [PK_userTypes];
ALTER TABLE [assadara_ssms_admin].[verificationCodeTypes] DROP CONSTRAINT [PK_verificationCodeTypes];
ALTER TABLE [assadara_ssms_admin].[academicSemesters] DROP CONSTRAINT [PK_academicSemesters];
ALTER TABLE [assadara_ssms_admin].[countries] DROP CONSTRAINT [PK_countries];
ALTER TABLE [assadara_ssms_admin].[departments] DROP CONSTRAINT [PK_departments];
ALTER TABLE [assadara_ssms_admin].[weeksPlans] DROP CONSTRAINT [PK_weeksPlans];
ALTER TABLE [assadara_ssms_admin].[actions] DROP CONSTRAINT [PK_actions];
ALTER TABLE [assadara_ssms_admin].[behavioralViolations] DROP CONSTRAINT [PK_behavioralViolations];
ALTER TABLE [assadara_ssms_admin].[periodsDetails] DROP CONSTRAINT [PK_periodsDetails];
ALTER TABLE [assadara_ssms_admin].[academicYears] DROP CONSTRAINT [PK_academicYears];
ALTER TABLE [assadara_ssms_admin].[accountStatus] DROP CONSTRAINT [PK_accountStatus];
ALTER TABLE [assadara_ssms_admin].[subjects] DROP CONSTRAINT [PK_subjects];
ALTER TABLE [assadara_ssms_admin].[branches] DROP CONSTRAINT [PK_branches];
ALTER TABLE [assadara_ssms_admin].[users] DROP CONSTRAINT [PK_users];
ALTER TABLE [assadara_ssms_admin].[academicWeeks] DROP CONSTRAINT [PK_academicWeeks];
ALTER TABLE [assadara_ssms_admin].[stages] DROP CONSTRAINT [PK_stages];
ALTER TABLE [assadara_ssms_admin].[employees] DROP CONSTRAINT [PK_employees];
ALTER TABLE [assadara_ssms_admin].[parents] DROP CONSTRAINT [PK_parents];
ALTER TABLE [assadara_ssms_admin].[refreshTokens] DROP CONSTRAINT [PK_refreshTokens];
ALTER TABLE [assadara_ssms_admin].[usersDocs] DROP CONSTRAINT [PK_usersDocs];
ALTER TABLE [assadara_ssms_admin].[verificationCodes] DROP CONSTRAINT [PK_verificationCodes];
ALTER TABLE [assadara_ssms_admin].[grades] DROP CONSTRAINT [PK_grades];
ALTER TABLE [assadara_ssms_admin].[schoolDayEvents] DROP CONSTRAINT [PK_schoolDayEvents];
ALTER TABLE [assadara_ssms_admin].[employeesFinance] DROP CONSTRAINT [PK_employeesFinance];
ALTER TABLE [assadara_ssms_admin].[employeesHR] DROP CONSTRAINT [PK_employeesHR];
ALTER TABLE [assadara_ssms_admin].[employeesJobs] DROP CONSTRAINT [PK_employeesJobs];
ALTER TABLE [assadara_ssms_admin].[students] DROP CONSTRAINT [PK_students];
ALTER TABLE [assadara_ssms_admin].[classrooms] DROP CONSTRAINT [PK_classrooms];
ALTER TABLE [assadara_ssms_admin].[gradesSubjects] DROP CONSTRAINT [PK_gradesSubjects];
ALTER TABLE [assadara_ssms_admin].[employeesActions] DROP CONSTRAINT [PK_employeesActions];
ALTER TABLE [assadara_ssms_admin].[teachersQuorums] DROP CONSTRAINT [PK_teachersQuorums];
ALTER TABLE [assadara_ssms_admin].[studentsViolations] DROP CONSTRAINT [PK_studentsViolations];
ALTER TABLE [assadara_ssms_admin].[classesStudents] DROP CONSTRAINT [PK_classesStudents];
ALTER TABLE [assadara_ssms_admin].[periods] DROP CONSTRAINT [PK_periods];
ALTER TABLE [assadara_ssms_admin].[teachersEdu] DROP CONSTRAINT [PK_teachersEdu];
ALTER TABLE [assadara_ssms_admin].[studentsProcedures] DROP CONSTRAINT [PK_studentsProcedures];
GO
-- drop all tables
------------------
DROP TABLE [assadara_ssms_admin].[lessonsFiles];DROP TABLE [assadara_ssms_admin].[subjects];DROP TABLE [assadara_ssms_admin].[branches];DROP TABLE [assadara_ssms_admin].[users];DROP TABLE [assadara_ssms_admin].[academicWeeks];DROP TABLE [assadara_ssms_admin].[stages];DROP TABLE [assadara_ssms_admin].[employees];DROP TABLE [assadara_ssms_admin].[parents];DROP TABLE [assadara_ssms_admin].[refreshTokens];DROP TABLE [assadara_ssms_admin].[usersDocs];DROP TABLE [assadara_ssms_admin].[verificationCodes];DROP TABLE [assadara_ssms_admin].[grades];DROP TABLE [assadara_ssms_admin].[schoolDayEvents];DROP TABLE [assadara_ssms_admin].[employeesFinance];DROP TABLE [assadara_ssms_admin].[employeesHR];DROP TABLE [assadara_ssms_admin].[employeesJobs];DROP TABLE [assadara_ssms_admin].[students];DROP TABLE [assadara_ssms_admin].[classrooms];DROP TABLE [assadara_ssms_admin].[gradesSubjects];DROP TABLE [assadara_ssms_admin].[employeesActions];DROP TABLE [assadara_ssms_admin].[teachersQuorums];DROP TABLE [assadara_ssms_admin].[studentsViolations];DROP TABLE [assadara_ssms_admin].[classesStudents];DROP TABLE [assadara_ssms_admin].[periods];DROP TABLE [assadara_ssms_admin].[teachersEdu];DROP TABLE [assadara_ssms_admin].[timeTables];DROP TABLE [assadara_ssms_admin].[academicYears];DROP TABLE [assadara_ssms_admin].[accountStatus];DROP TABLE [assadara_ssms_admin].[studentsProcedures];DROP TABLE [assadara_ssms_admin].[actions];DROP TABLE [assadara_ssms_admin].[behavioralViolations];DROP TABLE [assadara_ssms_admin].[periodsDetails];DROP TABLE [assadara_ssms_admin].[countries];DROP TABLE [assadara_ssms_admin].[departments];DROP TABLE [assadara_ssms_admin].[weeksPlans];DROP TABLE [assadara_ssms_admin].[docTypes];DROP TABLE [assadara_ssms_admin].[jobs];DROP TABLE [assadara_ssms_admin].[lessons];DROP TABLE [assadara_ssms_admin].[periodsFiles];DROP TABLE [assadara_ssms_admin].[majors];DROP TABLE [assadara_ssms_admin].[remedialProcedures];DROP TABLE [assadara_ssms_admin].[schools];DROP TABLE [assadara_ssms_admin].[userTypes];DROP TABLE [assadara_ssms_admin].[verificationCodeTypes];DROP TABLE [assadara_ssms_admin].[academicSemesters];DROP TABLE [assadara_ssms_admin].[jobsActions];GO